bookmark/urls.py
from django.urls import path

from .views import BookmarkList, BookmarkCreate, BookmarkUpdate, BookmarkDetail, BookmarkDelete

# namespace 이름 공간
# 다른 앱들과 url pattern 이름이 겹치는 것을 방지하기 위해서 사용
# namespace라는 인수가 존재

app_name = 'bookmark'
urlpatterns = [
    # path(url pattern, view, url pattern name),
    # 함수형 뷰 : 이름만
    # 클래스형 뷰 : 이름.as_view()
    # path, uuid, slug, int, str => custom converter
    # map/127.2222-34.3412/
    # convert -> location
    # map/<location:valu>/
    # converter
    # detail/abc/

    path('detail/<int:pk>/',BookmarkDetail.as_view(), name='detail'),
    path('delete/<int:pk>/',BookmarkDelete.as_view(), name='delete'),
    path('update/<int:pk>/',BookmarkUpdate.as_view(), name='update'),

    path('create/',BookmarkCreate.as_view(), name='create'),
    path('', BookmarkList.as_view(), name='index'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookmark.urls')),
]

bookmark/models.py
from django.db import models

# Create your models here.
# 모델의 형태 - 클래스

# models.Model을 상속받는 이유
# 상속 : 어떤 클래스가 부모 클래스를 상속받는다.
# ---> 부모 클래스가 가지고 있는 메서드나 속성값을 사용하기 위해서
# models.Model을 상속받은 이유?
# models.Model이 가지고 있는 메서드나 속성값을 사용하기 위해서
# models.Model : ORM 관련 기능들
# ORM 관련 기능 : DB를 추상화해서 코드로 조작할 수 있게 하는 기능
# 데이터를 추가, 수정, 검색, 삭제

class Bookmark(models.Model):
    site_name = models.CharField(max_length=50)
    url = models.URLField()
    contents = models.TextField(blank=True)
    # 작성자 -> 로그인한 유저 정보를 찾아서 추가
    # 작성자 != 로그인한 유저다
    # -> 모델 저장 직전에 직접 코드로 처리

    # 작성일 -> 서버 시간을 읽어서 timestamp값을 만들어 추가
    # 자동 옵션 auto_now, auto_now_add
    created = models.DateTimeField(auto_now_add=True)

    # DB에 적용 : makemigrations, migrate
    # python manage.py makemigrations bookmark
    # python manage.py migrate bookmark 0001

    # 관리자 페이지 목록에 표시될 내용
    # 확인 메시지에 출력되는 내용을 만들기 위해

    def __str__(self):
        return "Site name : "+self.site_name+", URL : "+self.url

    # 메타 클래스는 옵션 클래스 - 내가 상속을 받았는데, 속성값에 변경이 필요하다면
    class Meta:
        # 정렬 : 필드이름 -> 필드값 오름차순, -필드이름 -> 필드값 내림차순
        ordering = ['site_name']

    # 모델 클래스가 수정됐다고 해서 항상 migrate해야 하는 것은 아니다.
    # DB에 변경 사항이 반영돼야할 항목들만 migrate를 한다.

bookmark/views.py
from django.shortcuts import render

# Create your views here.
# 뷰 종류

# 클래스형 뷰 함수형 뷰는 서로 상호 기능 제약이 거의 없다.
# CRUDL에 특별한 처리를 추가해야 되는 경우
# 함수형뷰는 자유도가 클래스형 뷰에 비해서 높다
# 함수형 : def 뷰이름(request[,추가 인수]):
#           처리할 내용
# 처리할 코드를 직접 다 개발자가 작성
#

# CRUDL 에 관련 기능은 자주 사용하기 때문에 장고에서 제네릭
# 클래스형뷰는 생산성이 함수형뷰에 비해 높다.
# 클래스형 : class 뷰이름(제네릭뷰):
#             처리할 내용
# 제네릭 기능 외에 추가 적인 기능을 개발자가 작성
# 메서드 방식 - 커스터마이징에 관련된 메서드를 찾아야 한다.

# CRUD_L
from django.views.generic.list import ListView

# 클래스형 뷰의 이름은 자유
from .models import Bookmark

class BookmarkList(ListView):
    model = Bookmark
    # _list
    # 템플릿 종류
    # 읽어오는 데이터
    # 페이지네이션을 걸거나
    # 검색 쿼리를 적용하거나
    # 권한 채크

# 뷰를 만들었다 -> URL 연결
# CRUD 를 뷰를 만들고, URL연결 까지
from django.views.generic.edit import CreateView, UpdateView, DeleteView

class BookmarkCreate(CreateView):
    model = Bookmark
    # fileds는 사용자가 입력할 모델 필드를 정하는 것
    fields = ['site_name','url', 'contents']
    template_name_suffix = '_create'
    success_url = '/'
    # _create
    # _form

class BookmarkUpdate(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url', 'contents']
    template_name_suffix = '_update'
    success_url = '/'
    # _update
    # _form

class BookmarkDelete(DeleteView):
    model = Bookmark
    template_name_suffix = '_delete'
    success_url = '/'
    # _confirm_delete

from django.views.generic.detail import DetailView

class BookmarkDetail(DetailView):
    model = Bookmark
    # _detail

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}
Bookmark Create
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 com-md-4">
        <div class="alert alert-danger" role="alert">
            Please input bookmark information
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_delete.html
{% extends 'base.html' %}

{% block title %}
Bookmark Delate
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 com-md-4">
        <div class="alert alert-warning" role="alert">
            Do you want to delete {{object}}?
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete Ok">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}
Bookmark Detail
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 com-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{object.site_name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted"><a href="{{object.url}}" target="_blank">{{object.url}}</a>
                </h6>
                <p class="card-text">{{object.contents}}</p>
                <a href="{% url 'bookmark:update' object.id %}" class="btn btn-outline-warning">수정</a>
                <a href="{% url 'bookmark:delete' object.id %}" class="btn btn-outline-danger">삭제</a>
            </div>
        </div>
        <!--
        {{object.id}}<br>
        {{object.site_name}}<br>
        <a href="{{object.url}}" target="_blank" class="btn btn-outline-primary">링크</a>
        <a href="{% url 'bookmark:update' object.id %}" class="btn btn-outline-warning">수정</a>
        <a href="{% url 'bookmark:delete' object.id %}" class="btn btn-outline-danger">삭제</a>
        --!>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
<!--//
C - 객체를 생성 ->
R - 단일 object
U - 단일 object
D - 단일 object
L - 복수 객체 object_list

CSS Framework :
1. Bootstrap
2. Flat UI
3. Material Design Lite : Google - Android랑 디자인이 비슷하게

//-->
{% block title %}
Bookmark List
{% endblock %}


{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 com-md-4">
        <div align="right"><a href="{% url 'bookmark:create' %}" class="btn btn-success">Add Bookmark</a></div><br>

        {# bookmark 목록 출력하기 #}
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Site Name</th>
                <th scope="col">Link</th>
                <th scope="col">Modify</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{object.id}}</td>
                <td>
                    <a href="{% url 'bookmark:detail' object.id %}">{{object.site_name}}</a>
                </td>
                <td><a href="{{object.url}}" target="_blank">링크이동</a></td>
                <td><a href="{% url 'bookmark:update' object.id %}" class="btn btn-outline-warning">수정</a></td>
                <td><a href="{% url 'bookmark:delete' object.id %}" class="btn btn-outline-danger">삭제</a></td>
            </tr>
            <!-- <a href="{% url 'bookmark:detail' object.id %}">{{object.id}} {{object.site_name}}</a> {{object.url}}<br> --!>

            {% endfor %}
            </tbody>
        </table>
        <div align="right"> <button type="button" class="btn btn-primary">
            bookmark <span class="badge badge-light">4</span>
    </button></div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}
Bookmark Update
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 com-md-4">
        <div class="alert alert-info" role="alert">
Please update bookmark information
</div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Update" class="btn btn-success">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}